/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/app-header/AppHeader.vue')['default']
    AppHeaderCart: typeof import('./components/app-header/AppHeaderCart.vue')['default']
    ColorPicker: typeof import('./components/inputs/ColorPicker.vue')['default']
    ProductList: typeof import('./components/product-list/ProductList.vue')['default']
    ProductListCard: typeof import('./components/product-list/ProductListCard.vue')['default']
    ProductListCardSlider: typeof import('./components/product-list/ProductListCardSlider.vue')['default']
    ProductListCategories: typeof import('./components/product-list/ProductListCategories.vue')['default']
    ProductSearchbar: typeof import('./components/inputs/ProductSearchbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
